cmake_minimum_required(VERSION 3.10)
project(MonitorX)

set(CMAKE_C_STANDARD 99)    #C99 # lvgl officially support C99 and above
set(CMAKE_CXX_STANDARD 17)  #C17
set(CMAKE_CXX_STANDARD_REQUIRED ON)

SET(CMAKE_BUILD_TYPE DEBUG)
SET(EXECUTABLE_OUTPUT_PATH ${PROJECT_SOURCE_DIR})
SET(LIBRARY_OUTPUT_PATH ${PROJECT_SOURCE_DIR/bin})

ADD_SUBDIRECTORY(src)